#!/bin/bash

export NEMOVERSION_HOME="`pwd`";
export TASK=$1

#copy nemoversion plugin to $HOME/.nautilus/python-extensions/
function copy_nemoversion_plugin
{
    if [ -e "${HOME}/.nautilus/python-extensions/" ]; then
        echo "Copying nemoversion plugin to ${HOME}/.nautilus/python-extensions/"
        cp ${NEMOVERSION_HOME}/src/nemoversionplugin.py ${HOME}/.nautilus/python-extensions/
    else
        echo "Cannot find ${HOME}/.nautilus/python-extensions/"
        exit
    fi
}

#make python bytecode for nemoversion (default to $NEMOVERSION_HOME/bin)
function make_nemoversion_bytecode
{
    #TODO:
    echo "Compiling nemoversion..."
}

#launch a new nautilus instance (with nemoversion)
function new_nautilus_instance
{
    echo "Creating a new Nautilus instance..."
    mkdir /tmp/nemoversion
    export TMPDIR=/tmp/nemoversion
    nautilus --no-desktop
}

function rm_pyc_files
{
    echo "Removing all python compiled files..."
    find . -name "*.pyc" -exec rm '{}' ';'
}

#undo all envirioment changes
function undo_all_env_changes
{
    echo "Rolling back environment..."
    rm_pyc_files
    rm ${HOME}/.nautilus/python-extensions/nemoversionplugin.py
    rm -Rf /tmp/nemoversion
}

function run_tests
{
    echo "Running unit tests..."
    export PYTHONPATH=${NEMOVERSION_HOME}/src
    python ${NEMOVERSION_HOME}/src/nemoversion/tests/test.py
}

if [[ $TASK == "clear" ]]; then
    undo_all_env_changes
    exit 0
elif [[ $TASK == "pyc" ]]; then
    rm_pyc_files
    exit 0
elif [[ $TASK == "run_tests" ]]; then
    run_tests
    exit 0
elif [[ $TASK == "run" ]]; then
    make_nemoversion_bytecode
    copy_nemoversion_plugin
    new_nautilus_instance
    exit 0
fi
