#!/bin/bash

export NEMOVERSION_HOME="`pwd`";
export TASK=$1

#copy nemoversion plugin to $HOME/.nautilus/python-extensions/
function copy_nemoversion_plugin
{
    if [ -e "${HOME}/.nautilus/python-extensions/" ]; then
        echo "copying nemoversion plugin to ${HOME}/.nautilus/python-extensions/"
        cp ${NEMOVERSION_HOME}/src/nemoversionplugin.py ${HOME}/.nautilus/python-extensions/
    else
        echo "Cannot find ${HOME}/.nautilus/python-extensions/"
        exit
    fi
}

#make python bytecode for nemoversion (default to $NEMOVERSION_HOME/bin)
function make_nemoversion_bytecode
{
    #TODO:
    echo "Compiling nemoversion..."
}

#launch a new nautilus instance (with nemoversion)
function new_nautilus_instance
{
    echo "Creating a new Nautilus instance..."
    mkdir /tmp/nemoversion
    export TMPDIR=/tmp/nemoversion
    nautilus --no-desktop
}

#undo all envirioment changes
function undo_all_env_changes
{
    echo "Rolling back environment..."
    rm ${HOME}/.nautilus/python-extensions/nemoversionplugin.py
    rm -Rf /tmp/nemoversion
}


if [[ $TASK == "clear" ]]; then
    undo_all_env_changes
else
    make_nemoversion_bytecode
    copy_nemoversion_plugin
    new_nautilus_instance
fi
